version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file: .env  # Подключаем файл .env с переменными
    depends_on:
      - db  # Сначала поднимется база данных
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: Fitness_db  # Название базы данных
      POSTGRES_USER: postgres  # Логин для БД
      POSTGRES_PASSWORD: Narzullo2045  # Пароль для БД
    ports:
      - "5432:5432"  # Пробрасываем порт 5432 на хост
    volumes:
      - pg_data:/var/lib/postgresql/data  # Данные БД сохраняются в volume
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
    driver: local
